name: Check commit messages

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Create `main` branch
        run: |
          git branch --force main refs/remotes/origin/main
      - name: Check commit messages
        run: python ./ci/check_commit_messages.py
